numbers = [1,5,12,9,3,7,14,100,5,3,85,42]
letters = ['a','d','z','b','e','m','c']

print("Original Numbers List:", numbers)
print("Original Letters List:", letters)
print("Sorted Numbers List:", sorted(numbers))
print("Sorted Letters List:", sorted(letters))
print("Original Numbers List remains unchanged:", numbers)
print("Original Letters List remains unchanged:", letters)
numbers.sort()
letters.sort()
print("Numbers List after in-place sort:", numbers)
print("Letters List after in-place sort:", letters) 
print("Index of 9 in Numbers List:", numbers.index(9))
print("Index of 'c' in Letters List:", letters.index('c'))  
print("Number of times 5 appears in Numbers List:", numbers.count(5))
print("Number of times 'a' appears in Letters List:", letters.count('a'))
numbers.append(20)
letters.append('g') 
print("Numbers List after appending 20:", numbers)
print("Letters List after appending 'g':", letters)
numbers.remove(3)
letters.remove('d')
print("Numbers List after removing 3:", numbers)
print("Letters List after removing 'd':", letters)  
numbers.pop()
letters.pop()   
print("Numbers List after popping the last element:", numbers)
print("Letters List after popping the last element:", letters)  
numbers.pop(2)
letters.pop(1)  
print("Numbers List after popping element at index 2:", numbers)
print("Letters List after popping element at index 1:", letters)
numbers.insert(2, 15)
letters.insert(1, 'z')  
print("Numbers List after inserting 15 at index 2:", numbers)
print("Letters List after inserting 'z' at index 1:", letters)
numbers.reverse()
letters.reverse()   
print("Numbers List after reversing:", numbers)
print("Letters List after reversing:", letters)
result = "U" in letters
print("Is 'U' in Letters List?:", result)
result = 100 in numbers
print("Is 100 in Numbers List?:", result)
print("Reversed Numbers List using slicing:", numbers[::-1])
print("Reversed Letters List using slicing:", letters[::-1])    
letters.clear()  # Clear the letters list
print("Letters List after clearing:", letters)
